### ISSUE TITLE
Number of favorites add to bookmark lists

### ISSUE THREAD

**Issue by cniweb** [amshove/GC_little_helper#110]
Add number of favorites to bookmark lists.

**Comment by Torsten-** [comment]
Can you explain it a bit more? Waht exactyl do you mean?

**Comment by cniweb** [comment]
Add to bookmark lists to another column to appear with number of favorites.

**Comment by Torsten-** [comment]
Ah, ok - unfortunately this is not possible, because we work only with the information already available on the loaded page. The number of Favorites is not available at this page so we are not able to display it.

**Comment by cniweb** [comment]
Ohh, OK
