### ISSUE TITLE
Profile Link in Account Details

### ISSUE THREAD

**Issue by Confectrician** [amshove/GC_little_helper#112]
It would be nice to add a direct link to the User Profile (http://www.geocaching.com/profile/) in the Account Settings (http://www.geocaching.com/account/default.aspx) within the "Profile Details" Box.
![gc little helper profile details](https://cloud.githubusercontent.com/assets/7161177/4510353/8df44c18-4b29-11e4-99e8-815dacd9d172.PNG)
.

So it would be easy to switch to the own Profile after changing the Profile Details.

**Comment by Torsten-** [comment]
In the meantime gc.com changed the settings pages.
Now after saving you get the message "Your changes have been saved. View your profile" with a link.
So this issue can be closed.

**Comment by Confectrician** [comment]
Stimmt natürlich. Hatte das issue schon ganz vergessen.

You're right. I nearly had forgotten the issue already.

Thx 4 response.
