### ISSUE TITLE
PM cache details not shown vip/mail button to user when i have no premium account

### ISSUE THREAD

**Issue by pschonmann** [amshove/GC_little_helper#115]
![premium](https://cloud.githubusercontent.com/assets/6333844/5063530/c68ff476-6dea-11e4-937e-ed695c768151.jpg)

**Comment by Torsten-** [comment]
I've looked into this. The problim is, tha the ownername is not a link to his profile. GClh grabs the guid out of this link for the mail-button.
Unlikely the guid is nowhere on this page, so i can't build the correct links on this page.
