### ISSUE TITLE
Add myself into VIP-list

### ISSUE THREAD

**Issue by PontiacCZ** [amshove/GC_little_helper#122]
It would be useful to add myself into VIP-list so I could quickly glimpse at what I once wrote. 

I frequently open a-long-time-ago-found caches that are my friends' fresh finds, read their logs using VIP-list and I'm always curious about what I logged months/years ago. If I really want to know I have to click on the date link right below "Found it!" in the right-hand column.

It would be much more comfortable to be able to add my account into VIP-list so I could read my logs just like any other VIP.

**Comment by lukeIam** [comment]
It should possible:
- go to http://www.geocaching.com/profile/
- Click the VIP icon
- You should appear in the VIP list as "Me"

**Comment by PontiacCZ** [comment]
Great, it works! I just did not browse to my public profile so I could find the VIP icon next to my name. :-)
Thank you very much, I'm closing this issue.
