### ISSUE TITLE
Firefox 36 - does't work

### ISSUE THREAD

**Issue by DrakMrak** [amshove/GC_little_helper#137]
Tested on F36 32-bit/64-bit (Win 7/Win 8.1) - doesn't work...
GC-Little helper dont' working (Greasmonkey working well because another scripts working)

**Comment by lukeIam** [comment]
Please test: https://github.com/amshove/GC_little_helper/tree/newInitConcept
Am 26.02.2015 21:36 schrieb "DrakMrak" <notifications@github.com>:

**Comment by DrakMrak** [comment]
yup :) ok working ... it seems that it works well

**Comment by DrakMrak** [comment]
Thanks so much for the Czech Geocachers ;)
All working well

**Comment by PontiacCZ** [comment]
Well, I just tried the supplied link but nothing new there, only the old version 11.2 which does not work. What am I missing?

**Comment by DrakMrak** [comment]
a lot of people in czech tested supplied link and ok - now working.
try this link :) https://dl.dropboxusercontent.com/u/8232417/Greasemonkey/gc-little-helper/gc_little_helper.user.js
I prepare script (js) for short time than will be  the official version :) for my peoples...
Maybe it will help you too...

**Comment by DrakMrak** [comment]
:) Torsten - it is before the official version but this is works now for people who can not so much well with the computer... :)
sorry for my english is little horrible :)

**Comment by lukeIam** [comment]
Github also supports deeplinks:
https://raw.githubusercontent.com/amshove/GC_little_helper/newInitConcept/gc_little_helper.user.js
 Am 02.03.2015 08:57 schrieb "DrakMrak" <notifications@github.com>:

**Comment by DrakMrak** [comment]
ok
I do not work with github a lot of so thank you for the information

**Comment by PontiacCZ** [comment]
Used the deeplink and we're back on track! Looks like everything works as before. Thank you!

**Comment by lukeIam** [comment]
@Torsten- As we got only positive feedback and the current version is broken with FF36 we should think about making a release these days...

**Comment by lukeIam** [comment]
Sould be fixed in the current release
