### ISSUE TITLE
no gc little helper since the last updat

### ISSUE THREAD

**Issue by Mozique** [amshove/GC_little_helper#141]
GC little helper seems not added anymore to the geocaching website, 
I miss it!

**Comment by Torsten-** [comment]
We need more information. Which browser do you use? Firefox or Chrome? Which version? Waht exactyl happens?

**Comment by Mozique** [comment]
Hi, I use google Chrome.
Since the last update there is nothing visable in the website van Geocaching.com. 

Monique

**Comment by Cappa-d** [comment]
Same for me. Issues:

All settings gone incl. VIP list. New settings not accepted or stored.

Used Browser: Google Chrome Version 41.0.2272.101 m
GcLH: GC little helper 11.4

Worked until a few days ago

**Comment by lukeIam** [comment]
@Cappa-d looks like #140

**Comment by lukeIam** [comment]
Sould be fixed in the current release
