### ISSUE TITLE
GC little helper still doesn't work

### ISSUE THREAD

**Issue by Mozique** [amshove/GC_little_helper#144]
It doesn't fill in the templates..... What do I do wrong?

Gelogd om 14:49 uur met GCDroid
#owner# TFTC en het onderhouden
##found#

**Comment by lukeIam** [comment]
> What do I do wrong?
nothing :wink: it's a open bug...
see #143

**Comment by Mozique** [comment]
So it's simple, it doesn't work anymore??? No solution for this problem???

**Comment by lukeIam** [comment]
> No solution for this problem???

At the moment not.

> So it's simple, it doesn't work anymore???

If someone find the time for investigating and fixing the problem it will be done.
This problem is tracked with #143
