### ISSUE TITLE
vips not working anymore

### ISSUE THREAD

**Issue by repmeer** [amshove/GC_little_helper#156]
vip is not working anymore since a couple of days.

**Comment by klaubauter** [comment]
groundspeak has removed the "map_preview_canvas".
VIP List was shown before the map: no map, no VIP List ...

suggestion: Show VIP List before "Attributes "

                // Show VIP List
                var map = document.getElementById("ctl00_ContentBody_detailWidget");

**Comment by Torsten-** [comment]
Just try and make a pull request if it works ;-)

**Comment by PontiacCZ** [comment]
Good idea, klaubauter, it DOES work. Do the pull request and hopefully Torsten will be able to release a new version for others. :)

**Comment by repmeer** [comment]
How do we use the fork of klaubauter. That one is not available in the chrome webstore

**Comment by repmeer** [comment]
Thx for the fix.
