### ISSUE TITLE
links broken in Friends list

### ISSUE THREAD

**Issue by PontiacCZ** [amshove/GC_little_helper#162]
Links to "Found" and "Hidden" caches on [**Your friends**](https://www.geocaching.com/my/myfriends.aspx) page no longer work and return 500 server error. This behavior is caused by the string "**&disable_redirect**" in the link. Removing this suffix from the links makes them work again.

Example:
[https://www.geocaching.com/seek/nearest.aspx?ul=solitare.cz&disable_redirect](https://www.geocaching.com/seek/nearest.aspx?ul=solitare.cz&disable_redirect) - returns error 500.
[https://www.geocaching.com/seek/nearest.aspx?ul=solitare.cz](https://www.geocaching.com/seek/nearest.aspx?ul=solitare.cz) - OK.

**Comment by PontiacCZ** [comment]
I fixed the invalid links and created a pull request #163. Would you please take a few minutes, review the changes and release a fixed version for others?

**Comment by lukeIam** [comment]
@PontiacCZ 
Thanks for fixing!

I'll try to make a release (also with some changes from geoclub.de)

**Comment by lukeIam** [comment]
> @PontiacCZ
> Thanks for fixing!
> 
> I'll try to make a release (also with some changes from geoclub.de)

There is fork of GClh which is actively maintained:
https://github.com/2Abendsegler/GClh

So I decided not to fix anything here anymore and suggest changing to GClh II.

**Comment by PontiacCZ** [comment]
OK, I have just installed the GClh II and started discovering it. I guess it will be okay. 
Maybe you could write a message here on the main page about GClh II ... oh, you already did! :-) 

Perfect, I consider this issue closed (and probably this whole project, right? ;-) ) But there is no reason to be sad, the idea lives on!
