### ISSUE TITLE
Integrate Optimap TSP solver

### ISSUE THREAD

**Issue by syphernl** [amshove/GC_little_helper#52]
I'm a big fan of GC Little helper (although its not so little anymore :-)). It would be nice if this addon would implement support for Optimap. 

Optimap is a webapplication/site that can be used to enter coordinates and find the fastest route between the points. I always use to make the most optimal Geocaching route

Routes can be added with GET parameters `nameX` and `locX` where X is a number from 0 to .... The end result is an URL like:

```
http://www.optimap.net/index.php?name0=Start&loc0=(60,10)&name1=First stop&loc1=(59.5,9.8)&name2=2nd stop&loc2=Askroken 51
```

How I see it:
* A button on the cache page (or even/also checkboxes on the search results/bookmark pages etc) that adds the cache name, code & coordinates into a local cache (GM_setValue)
* Also, a button to remove the cache from the route/queue would be nice.
* A button to "Make Optimap" which encodes the saved arguments into the URL and opens a new window to it.
* Don't forget to use the Home coordinates (which GC Little Helper already knows) as first location

The downside is that I haven't found a way to change the route options, especially since we're generally using this when cycling rather than car routes (default setting).

**Comment by Torsten-** [comment]
By now there is no chance to adding GCTour-functions to GClh. There is enough work to keep GClh running :-)
