### ISSUE TITLE
Mail Link template disappears.

### ISSUE THREAD

**Issue by mcl1080** [amshove/GC_little_helper#94]
Mail link next to the user name (in cache and TB Listings) - this is written directly to the Cache-/TB-Name, GCcode and Owner name in the email text field.

When I click the email button it opens the new mail and adds the cache name and coord.info link, but when i click to add my message the text disappears.

**Comment by dagger38** [comment]
still not working for me , gc little helper 11.2 on google chrome?

**Comment by Torsten-** [comment]
Is this still a current problem or is it solved?

**Comment by dagger38** [comment]
see post 4 jan...
Click on the mail icon , go to the mail form and no gc code no cache name?
blank page from the beginning!

**Comment by lukeIam** [comment]
Found the problem: chrome do not let us remove the onfocus listener from GS

-> Working on a workaround
